### PR TITLE
New extension modules and grep extension

### PR DESCRIPTION
**Pull request by jfdenise**
Module for aesh and readline extensions.
Ported grep command on aesh 1.0 API and moved to aesh module.
Other extensions (that don't compile) will have to be moved and ported to aesh 1.0.

### CODE REVIEW

**Comment by stalep** [comment]
thanks!

**Comment by jfdenise** [comment]
You merged before aesh PR, it will not build.

JF

**Comment by stalep** [comment]
dang! ok, ill merge the æsh pr, but please add tests :)

**Comment by jfdenise** [comment]
Sure,

I prefer to send PR earlier in order for us to exchange prior to investe 
in tests. But this time you went too fast....

JF

**Pull request merged**
